server:
  port: 8088

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: false
        dialect : org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.type.descriptor.sql: trace

#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        trace: false
#        web-allow-others: true

